apiVersion: skaffold/v3
kind: Config
metadata:
  name: ghcr-actions-test
build:
  artifacts:
  - image: ghcr-actions-test
    ko:
      dependencies:
        paths:
        - go.mod
        - '**/*.go'
        ignore:
        - '**/*_test.go'
  tagPolicy:
    inputDigest: {}
manifests:
  rawYaml:
  - manifests/*.yaml
portForward:
- resourceType: deployment
  resourceName: hello
  port: 8080
profiles:
- name: release
  patches:
  - op: add
    path: /build/artifacts/0/platforms
    value:
    - linux/amd64
    - linux/arm64
  - op: add
    path: /build/artifacts/0/ko/labels
    value:
      org.opencontainers.image.description: Image description max 512 characters.
      org.opencontainers.image.licenses: Apache-2.0
      org.opencontainers.image.revision: '{{.REVISION}}'
      org.opencontainers.image.source: '{{.SOURCE}}'
      org.opencontainers.image.title: ghcr-actions-test
      org.opencontainers.image.url: '{{.URL}}'
      org.opencontainers.image.vendor: Company LLC
      org.opencontainers.image.version: '{{.VERSION}}'
  - op: add
    path: /build/artifacts/0/ko/ldflags
    value:
    - -s
    - -w
