apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: ghcr.io/halvards/ghcr-actions-test:v0.1.11@sha256:661a67960961dde1e05d8e6c9a9d7eca1d595cbd19825c398382d99d97ee5bd2
        name: hello
        ports:
        - containerPort: 8080
