apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - name: hello
      image: ghcr.io/halvards/ghcr-actions-test:v0.0.5@sha256:3181c3224cd6c5bc0bb7d33d66a58741a5f52e73d93b8732be45e4122267face # kpt-set: ${image}
