# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
    paths-ignore:
    - '**.md'
    - 'docs/**'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      CGO_ENABLED: '0'
      COSIGN_VERSION: v1.4.1
      GGCR_VERSION: v0.7.0
      KPT_VERSION: v1.0.0-beta.10
      KUSTOMIZE_VERSION: v4.4.1
      SKAFFOLD_VERSION: 524a6b3914101af15fadf2eb3489e578a9c71f78
      SKAFFOLD_CACHE_ARTIFACTS: 'false'
      SKAFFOLD_DETECT_MINIKUBE: 'false'
      SKAFFOLD_INTERACTIVE: 'false'
      SKAFFOLD_OFFLINE: 'true'
      SKAFFOLD_UPDATE_CHECK: 'false'

    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set image env vars
      run: |
        echo IMAGE_REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        RC_VERSION=${GITHUB_REF#refs/tags/}
        echo VERSION=${RC_VERSION%-rc*} >> $GITHUB_ENV

    - name: Print Go env
      run: |
        echo HOME=$HOME
        echo PATH=$PATH
        go env

    - name: Run unit tests
      run: |
        go test -v -count=1 -short -timeout=3m -vet=asmdecl,assign,atomic,bools,buildtag,cgocall,composites,copylocks,errorsas,httpresponse,loopclosure,lostcancel,nilfunc,printf,shift,stdmethods,structtag,tests,unmarshal,unreachable,unsafeptr,unusedresult ./...

    # TODO: Download Skaffold binary (instead of compiling from source) after https://github.com/GoogleContainerTools/skaffold/pull/6944 is included in a release.
    # - name: Install Skaffold
    #   run: |
    #     mkdir -p $HOME/.local/bin
    #     curl -sSLo $HOME/.local/bin/skaffold "https://storage.googleapis.com/skaffold/releases/${SKAFFOLD_VERSION}/skaffold-$(go env GOOS)-$(go env GOARCH)"
    #     chmod +x $HOME/.local/bin/skaffold

    - name: Clone Skaffold Git repo
      run: |
        SKAFFOLD_SRC=$(mktemp -d)
        echo SKAFFOLD_SRC=$SKAFFOLD_SRC >> $GITHUB_ENV
        git clone --no-checkout https://github.com/GoogleContainerTools/skaffold.git $SKAFFOLD_SRC

    - name: Build Skaffold from source
      run: |
        git checkout $SKAFFOLD_VERSION
        go build -o $HOME/.local/bin/skaffold ./cmd/skaffold
      working-directory: ${{ env.SKAFFOLD_SRC }}

    - name: Create release branch
      run: |
        git checkout -B release-$VERSION

    - name: Populate version number in embedded file
      run: |
        echo $VERSION > pkg/version/version.txt

    - name: Commit and push to release branch with new version number
      run: |
        git add pkg/version/version.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Update binary version to $VERSION"
        git push --force origin release-$VERSION

    - name: Set image label env vars
      run: |
        echo REVISION=$(git rev-parse HEAD) >> $GITHUB_ENV
        echo SOURCE=${{ github.server_url }}/${{ github.repository }}.git >> $GITHUB_ENV
        echo URL=${{ github.server_url }}/${{ github.repository }} >> $GITHUB_ENV

    - name: Build binaries
      run: |
        GOOS=darwin GOARCH=amd64 go build -v -trimpath -ldflags="-s -w" -o ghcr-actions-test_Darwin_x86_64 .
        GOOS=darwin GOARCH=arm64 go build -v -trimpath -ldflags="-s -w" -o ghcr-actions-test_Darwin_arm64 .
        GOOS=linux  GOARCH=amd64 go build -v -trimpath -ldflags="-s -w" -o ghcr-actions-test_Linux_x86_64 .
        GOOS=linux  GOARCH=arm64 go build -v -trimpath -ldflags="-s -w" -o ghcr-actions-test_Linux_aarch64 .

    - name: Authenticate to container image registry
      uses: docker://gcr.io/go-containerregistry/crane:${{ env.GGCR_VERSION }}
      with:
        args: auth login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ github.token }}

    - name: Build and push container images
      run: |
        skaffold build \
          --file-output ${{ runner.temp }}/skaffold-artifacts.json \
          --profile release \
          --push \
          --tag $VERSION
      env:
        SKAFFOLD_DEFAULT_REPO: ${{ env.REGISTRY }}/${{ github.repository_owner }}

    - name: Render release manifest
      run: |
        skaffold render \
          --build-artifacts ${{ runner.temp }}/skaffold-artifacts.json \
          --digest-source none \
          --output ghcr-actions-test_manifest.yaml \
          --profile release

    - name: Get image name with digest
      run: |
        echo -n IMAGE_NAME= >> $GITHUB_ENV
        echo $(jq -r '.builds[] | select(.imageName=="ghcr-actions-test") | .tag' ${{ runner.temp }}/skaffold-artifacts.json) >> $GITHUB_ENV

    - name: Update latest tag
      uses: docker://gcr.io/go-containerregistry/crane:${{ env.GGCR_VERSION }}
      with:
        args: tag $IMAGE_NAME latest

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: ${{ env.COSIGN_VERSION }}

    - name: Sign the images with GitHub OIDC Token
      run: cosign sign --force --recursive --upload $IMAGE_NAME
      env:
        COSIGN_EXPERIMENTAL: 1

    - name: Create checksums file
      run: shasum -a 256 ghcr-actions-test_* > SHA256SUMS

    - name: Create release body file
      run: |
        cat << EOF > ${{ runner.temp }}/body.md
        ## Images

        GitHub Container Registry:

            $IMAGE_NAME
        EOF

    - name: Set image name in Kustomize manifest
      uses: docker://k8s.gcr.io/kustomize/kustomize:${{ env.KUSTOMIZE_VERSION }}
      with:
        args: edit set image ghcr-actions-test=$IMAGE_NAME
      working-directory: manifests

    - name: Create kpt setter values file
      uses: actions-hub/kubectl@v1.21.2
      with:
        args: create configmap setters --from-literal "image=${{ env.IMAGE_NAME }}" --dry-run=client --output yaml > setters.yaml
      working-directory: manifests

    - name: Update version in readme
      run: |
        sed -i~ "s/VERSION=.*/VERSION=$VERSION/" README.md

    - name: Commit and push to release branch with new version and image ref
      run: |
        git add README.md manifests
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Update version in readme and manifest to $VERSION"
        git push --force origin release-$VERSION

    - name: Set release env vars
      run: |
        echo COMMITISH=$(git rev-parse HEAD) >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        body_path: ${{ runner.temp }}/body.md
        commitish: ${{ env.COMMITISH }}

    - name: Upload binary darwin amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghcr-actions-test_Darwin_x86_64
        asset_name: ghcr-actions-test_Darwin_x86_64
        asset_content_type: application/octet-stream

    - name: Upload binary darwin arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghcr-actions-test_Darwin_arm64
        asset_name: ghcr-actions-test_Darwin_arm64
        asset_content_type: application/octet-stream

    - name: Upload binary linux amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghcr-actions-test_Linux_x86_64
        asset_name: ghcr-actions-test_Linux_x86_64
        asset_content_type: application/octet-stream

    - name: Upload binary linux arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghcr-actions-test_Linux_aarch64
        asset_name: ghcr-actions-test_Linux_aarch64
        asset_content_type: application/octet-stream

    - name: Upload manifest file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghcr-actions-test_manifest.yaml
        asset_name: ghcr-actions-test_manifest.yaml
        asset_content_type: application/x-yaml

    - name: Upload checksum file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: text/plain

    - name: Update version in readme on main branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git reset --hard
        git remote update
        git checkout main
        git pull --no-edit --no-rebase --strategy-option=theirs origin
        sed -i~ "s/VERSION=.*/VERSION=$VERSION/" README.md
        git add README.md
        git commit -m "Update version in readme to $VERSION"
        git pull --no-edit --no-rebase --strategy-option=ours origin
        git push origin main
